# IR Pump-Probe Spectroscopy Control Interface Hardware Configuration
# Updated with actual hardware specifications from vendor documentation

[system]
# Global system settings
data_directory = "/path/to/data"
log_level = "INFO"
experiment_timeout = 3600
default_units = "microns"  # or "cm1" for wavenumbers

[system.synchronization]
# Master timing and synchronization settings
master_clock = "quantum_composers_9524"
trigger_mode = "external"
repetition_rate = 1000  # Hz
sync_timeout = 5.0  # seconds

# ============================================================================
# ARDUINO UNO R4 MINIMA - MUX Controller
# ============================================================================
[arduino_uno_r4]
device_type = "Arduino Uno R4 Minima"
connection_type = "USB"
port = "COM3"  # Windows: COM3, Linux: /dev/ttyUSB0, macOS: /dev/cu.usbmodem*
baud_rate = 115200
timeout = 2.0
description = "MUX controller for sample positioning"

[arduino_uno_r4.parameters]
# MUX control parameters
num_positions = 10  # Number of sample positions
default_position = 1
position_delay = 0.5  # seconds to wait after position change
heartbeat_interval = 1.0  # seconds between status checks

[arduino_uno_r4.control_parameters]
auto_connect = true
validate_position = true
enable_heartbeat = true

# ============================================================================
# CONTINUUM ND:YAG LASER (SURELITE) - Pump Source
# ============================================================================
[continuum_ndyag]
device_type = "Continuum Surelite Nd:YAG Laser"
connection_type = "TTL"  # Controlled via Signal Generator TTL output
description = "Pump laser controlled via TTL signals from Signal Generator"

[continuum_ndyag.parameters]
# Laser specifications from manual
wavelength = 1064  # nm (fundamental)
pulse_energy_max = 850  # mJ at 1064nm
pulse_width = 4  # ns FWHM
repetition_rate_max = 10  # Hz
beam_diameter = 9  # mm

[continuum_ndyag.control_parameters]
# TTL control via Signal Generator
ttl_channel = "A"  # Signal generator output channel
trigger_polarity = "positive"  # positive or negative edge
trigger_width = 10  # microseconds
safety_interlock = true
warmup_time = 900  # seconds (15 minutes)

[continuum_ndyag.safety]
# Safety parameters from manual
max_pulse_energy = 850  # mJ
min_pulse_interval = 100  # ms (10 Hz max)
interlock_required = true
key_switch_required = true

# ============================================================================
# DAYLIGHT MIRCAT LASER - Probe Source
# ============================================================================
[daylight_mircat]
device_type = "Daylight MIRcat QCL"
connection_type = "USB"
port = "AUTO"  # Auto-detect USB device
sdk_path = "C:/Program Files/Daylight Solutions/MIRcat SDK"  # Windows default
description = "Mid-IR tunable probe laser"

[daylight_mircat.parameters]
# Laser specifications from datasheet
wavelength_min = 5.5  # microns
wavelength_max = 12.0  # microns
wavelength_resolution = 0.001  # microns
num_qcls = 4  # Number of QCL modules
default_wavelength = 8.0  # microns

[daylight_mircat.communication]
# SDK communication parameters
comm_type = "SERIAL"  # MIRcatSDK_COMM_SERIAL
baud_rate = 115200  # MIRcatSDK_SERIAL_BAUD1
auto_detect_port = true
timeout = 5.0

[daylight_mircat.control_parameters]
# Laser operation modes from SDK constants
default_mode = "PULSED"  # MIRcatSDK_MODE_PULSED, CW, CW_MOD
pulse_mode = "INTERNAL"  # MIRcatSDK_PULSE_MODE_INTERNAL, EXTERNAL_TRIGGER
pulse_rate = 1000  # Hz
pulse_width = 500  # nanoseconds
temperature_stabilization = true
auto_arm = false  # Require manual arming for safety

[daylight_mircat.safety]
# Safety parameters from manual
interlock_required = true
key_switch_required = true
temperature_monitoring = true
max_temperature = 25  # Celsius
emission_timeout = 300  # seconds

# ============================================================================
# PICOSCOPE 5244D - Oscilloscope
# ============================================================================
[picoscope_5244d]
device_type = "PicoScope 5244D MSO"
connection_type = "USB3"
sdk_path = "C:/Program Files/Pico Technology/SDK"  # Windows default
description = "4-channel oscilloscope for data acquisition"

[picoscope_5244d.parameters]
# Hardware specifications from datasheet
num_channels = 4
max_sample_rate = 1000000000  # 1 GS/s
memory_depth = 512000000  # 512 MS
bandwidth = 200000000  # 200 MHz
resolution_bits = 12  # 12-bit ADC

[picoscope_5244d.acquisition]
# Default acquisition settings
default_range = "5V"  # ±5V input range
default_coupling = "DC"  # DC or AC coupling
default_timebase = 1000  # nanoseconds per sample
trigger_channel = "A"
trigger_threshold = 0.1  # Volts
trigger_direction = "RISING"

[picoscope_5244d.channels]
# Channel-specific settings
channel_a_enabled = true
channel_b_enabled = true
channel_c_enabled = false
channel_d_enabled = false
channel_a_range = "5V"
channel_b_range = "5V"

[picoscope_5244d.streaming]
# Streaming mode parameters
buffer_size = 100000
overview_buffer_size = 1000
auto_stop = false
streaming_interval = 100  # microseconds

# ============================================================================
# QUANTUM COMPOSERS 9524 - Signal Generator
# ============================================================================
[quantum_composers_9524]
device_type = "Quantum Composers 9524"
connection_type = "USB"
port = "COM4"  # Windows: COM4, Linux: /dev/ttyUSB1
baud_rate = 115200
timeout = 2.0
description = "Signal generator for system synchronization"

[quantum_composers_9524.parameters]
# Hardware specifications from datasheet
num_channels = 8
max_frequency = 100000000  # 100 MHz
min_pulse_width = 5  # nanoseconds
max_delay = 1000  # seconds
resolution = 0.25  # nanoseconds

[quantum_composers_9524.communication]
# Serial communication settings from manual
data_bits = 8
parity = "none"
stop_bits = 1
flow_control = "none"
command_terminator = "\r\n"  # 0D,0A hex

[quantum_composers_9524.channels]
# Channel assignments based on wiring diagram
channel_a_function = "ndyag_trigger"  # TTL to Nd:YAG laser
channel_b_function = "mircat_trigger"  # TTL to MIRcat laser
channel_c_function = "picoscope_trigger"  # Trigger to PicoScope
channel_d_function = "lockin_reference"  # Reference to lock-in amplifier

[quantum_composers_9524.timing]
# Default timing parameters
master_frequency = 1000  # Hz
channel_a_delay = 0  # microseconds
channel_b_delay = 10  # microseconds
channel_c_delay = 5  # microseconds
channel_d_delay = 0  # microseconds
pulse_width = 10  # microseconds

# ============================================================================
# ZURICH HF2LI - Lock-in Amplifier
# ============================================================================
[zurich_hf2li]
device_type = "Zurich Instruments HF2LI"
connection_type = "USB"
device_id = "dev####"  # Replace with actual device serial number
labone_path = "C:/Program Files/Zurich Instruments/LabOne"  # Windows default
description = "Dual-phase lock-in amplifier for signal processing"

[zurich_hf2li.parameters]
# Hardware specifications from manual
frequency_range_min = 0.01  # Hz
frequency_range_max = 50000000  # 50 MHz
input_range_max = 1.5  # Volts
num_demodulators = 6
num_oscillators = 2
sampling_rate = 210000000  # 210 MS/s

[zurich_hf2li.communication]
# LabOne API settings
api_level = 6  # API level for compatibility
server_host = "localhost"
server_port = 8004
timeout = 20.0  # seconds
auto_connect = true

[zurich_hf2li.demodulator]
# Default demodulator settings
demod_index = 0  # Primary demodulator
time_constant = 0.001  # seconds
filter_order = 4
input_range = 1.0  # Volts
ac_coupling = false

[zurich_hf2li.oscillator]
# Reference oscillator settings
osc_index = 0  # Primary oscillator
frequency = 1000  # Hz (matches system repetition rate)
amplitude = 0.1  # Volts

# ============================================================================
# EXPERIMENT COORDINATION
# ============================================================================
[experiment]
# Global experiment parameters
default_scan_range = [6.0, 10.0]  # microns
default_scan_points = 100
default_integration_time = 1.0  # seconds per point
data_format = "HDF5"  # or "CSV", "NPY"

[experiment.timing]
# Experiment timing coordination
pre_scan_delay = 2.0  # seconds
post_scan_delay = 1.0  # seconds
point_to_point_delay = 0.1  # seconds
laser_stabilization_time = 0.5  # seconds

[experiment.safety]
# Safety limits for automated experiments
max_scan_time = 7200  # seconds (2 hours)
max_laser_on_time = 3600  # seconds (1 hour)
temperature_check_interval = 60  # seconds
auto_shutdown_on_error = true

# ============================================================================
# CALIBRATION AND VALIDATION
# ============================================================================
[calibration]
# System calibration parameters
wavelength_calibration_file = "wavelength_cal.json"
power_calibration_file = "power_cal.json"
detector_calibration_file = "detector_cal.json"
last_calibration_date = "2025-08-08"

[validation]
# System validation and health checks
enable_startup_checks = true
enable_periodic_checks = true
check_interval = 300  # seconds (5 minutes)
health_check_timeout = 30  # seconds

